BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls',namespace='blogs')),
    path('accounts/',include('useraccounts.urls',namespace='useraccounts')),
]

blogs/urls.py
from django.urls import path
from .views import CreatePostView, DisplayPostView, DeletePostView , UpdatePostView ,DetailPostView, UserDetailView

app_name = 'blogs'

urlpatterns=[
    path('',DisplayPostView.as_view(),name='display'),
    path('create/',CreatePostView.as_view(), name='create'),
    path('update/<int:blog_id>/',UpdatePostView.as_view(),name='update'),
    path('detail/<int:blog_id>/',DetailPostView.as_view(),name='detail'),
    path('delete/<int:blog_id>/',DeletePostView.as_view(),name='delete'),
    path('<str:author>/<int:author_id>/',UserDetailView.as_view(),name ='profile'),

]

useraccounts/urls.py
from django.urls import path
from .views import SignUpView,ProfileUpdateView,LoginView,LogoutView,UserBlogListView

app_name = 'useraccounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('edit/<int:author_id>/', ProfileUpdateView.as_view(), name='edit'),
    path('<str:author>/<int:author_id>/',UserBlogListView.as_view(), name='blog_list'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('activate/<uidb64>/<token>/',ActivateView.as_view(), name='activate'),
]

blogs/models.py
from django.db import models
from django.urls import reverse
import uuid
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.conf import settings

# Create your models here.

def image_path(_,filename):
    extension = filename.split('.')[-1]
    unique_id = uuid.uuid4().hex
    new_filname = unique_id+'.'+extension
    return 'post/'+new_filname

class Blogs(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=image_path,null=True,blank=True)
    slug = models.SlugField(max_length=200,editable=True,null=True,blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='blogs',default=1)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # count = models.IntergerField(default=0)

    class Meta :
        ordering = ('-created',)

    def save(self,*args,**kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Blogs,self).save(*args,**kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogposts:user_post_list', kwargs={
            'author': self.author.username, 'author_id': self.author.id})

blogs/forms.py
from django import forms
from .models import Blogs
from ckeditor.widgets import CKEditorWidget

class BlogCreateForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Blogs
        fields = ['title','author','image','body']


    def __init__(self,*args,**kwargs):
        super(BlogCreateForm,self).__init__(*args,**kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({'class':'form-control'})

        self.fields['author'].widget.attrs.update({'style': 'display:none;'})
        self.fields['author'].label = ''


class BlogsForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Blogs
        fields = ['title', 'image', 'body']
        required = {
                'author': False
            }

    def __init__(self, *args, **kwargs):
        super(BlogsForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True, *args, **kwargs):
        obj = super(BlogsForm, self).save(commit=False, *args, **kwargs)
        from django.utils.text import slugify
        obj.slug = slugify(obj.title)
        if commit:
            obj.save()
        return obj

blogs/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from .forms import BlogCreateForm,BlogsForm
from .models import Blogs
from django.views.generic import ListView,CreateView,UpdateView,DetailView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator


class DisplayPostView(ListView):
    model = Blogs
    template_name = 'blogs/index.html'
    context_object_name = 'posts'

    def get_queryset(self,*args,**kwargs):
        queryset= super(DisplayPostView,self).get_queryset(*args,**kwargs)

        queryset= queryset.order_by('-created')


        return queryset

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super(DisplayPostView,self).get_context_data(*args,**kwargs)
        context['featured']= Blogs.objects.order_by('-created')[:2]
        context['authors'] = User.objects.all()
        context['Blogs']= Blogs.objects.all()[:5]

        return context


class DetailPostView(DetailView):
    model = Blogs
    form_class = BlogCreateForm

    context_object_name = 'posts'
    pk_url_kwarg = 'blog_id'
    slug_url_kwarg = 'slug'
    template_name = 'blogs/detail_blog.html'



class UserDetailView(DetailView):
    model = Blogs
    template_name = 'blogs/profile.html'
    context_object_name = 'posts'
    pk_url_kwarg = 'author_id'
    slug_url_kwarg = 'author'





@method_decorator(login_required(login_url='useraccounts/login/'), name ='dispatch')
class CreatePostView(CreateView):
    template_name = 'blogs/create_blog.html'
    form_class = BlogCreateForm
    success_message = "Post was created Successfully"

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author = self.request.user
        form.save()
        form.save_m2m()
        return super().form_valid(form)

@method_decorator(login_required(login_url='/useraccounts/login/'), name='dispatch')
class UpdatePostView(UpdateView):
    model = Blogs
    form_class = BlogsForm
    pk_url_kwarg = 'id'
    author_url_kwarg = 'author'
    template_name = 'blogs/update_blog.html'
    success_message = "Successfully Updated"

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        pk = self.kwargs.get(self.pk_url_kwarg)
        author = self.kwargs.get(self.author_url_kwarg)
        if pk is not None and author is not None:
            queryset = queryset.filter(author__id=pk).filter(author__username=author)

        if pk is None and author is  None:
            return "Attribute Error"

        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            return "model not found"

        return obj

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author= self.request.user
        form.save()
        form.save_m2m()
        return redirect('/blogs/index.html')




@method_decorator(login_required(login_url='/accounts/login/'), name='dispatch')
class DeletePostView(DeleteView):
    def get(self, request, author_id):
        obj = get_object_or_404(Blogs,author__id=author_id)
        obj.delete()
        messages.success(request,"Delete Successfully")
        return redirect('blogs:user_detail',request.user.username,request.user.id)

blogs/templates/blogs/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE HTML>
<html>
<head>
 <title>{% block title %} Blog {% endblock title %}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Voguish Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />


	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,700' rel='stylesheet' type='text/css'>
	<link href="{% static 'blogs/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
	<link href="{% static 'blogs/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


	<script src="{% static 'blogs/js/jquery.min.js' %}"></script>
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<script src="{% static 'blogs/js/responsiveslides.min.js' %}"></script>
	<script>
    	$(function () {
    		$("#slider").responsiveSlides({
				auto: true,
				nav: true,
				speed: 500,
				namespace: "callbacks",
				pager: true,
			});
		});
	
 	 </script>


</head>
<body>
<!-- header -->
<div class="container">
	{% include 'blogs/navbar.html' %}
	
	{% block content %}
    {% endblock content %}

	{% include 'blogs/footer.html' %}
</div>

    
    
</body>
</html>

blogs/templates/blogs/create_blog.html
{% extends 'blogs/base.html' %}
{% block title %}
Create Post

{% endblock %}

{% block content %}
<div class="row">
  <div class="container">
    <div
      class="col-md mt-5 mx-auto justify-content-center align-items-center"
    >
      <div class="m-5 shadow p-5 text-dark">
        <h1>Create a Post</h1>
        <p>Please, use the following form to log-in:</p>

        <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}

          <input class="btn btn-secondary px-5" type="submit"  />
        </form>
        </p>
      </div>
    </div>
  </div>
</div>



{% endblock %}

blogs/templates/blogs/detail_blog.html
{% extends 'blogs/base.html' %}
{% block title %}
BlogPosts|{{ objects.title }}

{% endblock %}

{% block content %}
<!-- header -->
	<!-- Blog -->
	<div class="container">
		<div class="blog">

		<div class="blog-content">
					<div class="blog-content-left">
						<div class="blog-articals">

						<div class="blog-artical">
							<div class="blog-artical-info">
								<div class="blog-artical-info-head">
									<h2><a href="#">{{ posts.title }}</a></h2>
									<h6>Posted on, {{ posts.created }} by <a href="#">{{posts.author.first_name}}</a></h6>
								</div>
								<div class="blog-artical-info-text">

									<img src="/media/{{post.image}}" height="50px" width="100px" alt="photo">


									<p class="pl-0 pt-3 pr-3 pb-3 mt-3">{{ posts.body }}</p>
								</div>
								<!-- <div class="artical-links">
		  						 	<ul>
		  						 		<li><small> </small><span>june 14, 2013</span></li>
		  						 		<li><a href="#"><small class="admin"> </small><span>admin</span></a></li>
		  						 		<li><a href="#"><small class="no"> </small><span>No comments</span></a></li>
		  						 		<li><a href="#"><small class="posts"> </small><span>View posts</span></a></li>
		  						 		<li><a href="#"><small class="link"> </small><span>permalink</span></a></li>
		  						 	</ul>
		  						 </div> -->
							</div>
							<div class="clearfix"> </div>
						</div>


					</div>

					</div>

					</div>
					<div class="clearfix"> </div>

				</div>
		</div>
		<!-- /Blog -->


{% endblock content %}

blogs/templates/blogs/footer.html
<div class="footer">
		<div class="col-md-4 foot-1">
			<h4>Quick Links</h4>
			<ul>
				<li><a href="https://medium.com/" target="_new">|| Medium  </a></li>
				<li><a href="https://geeksforgeeks.com/" target="_new">||   GeeksForGeeks</a></li>
				<li><a href="https://curiositydaily.com/" target="_new">||   Curiosity</a></li>
			</ul>
		</div>
		<div class="col-md-4 foot-1">
			<h4>Favorite Resources</h4>
			<ul>
				<li><a href="#">||   Characteristic words</a></li>
				<li><a href="#">||   combined with a handful</a></li>
				<li><a href="#">||   which looks reasonable</a></li>
			</ul>
		</div>
		<div class="col-md-4 foot-1">
			<h4>About Us</h4>
			<ul>
				<li><a href="https://facebook.com" target="_blank">||  Facebook</a></li>
				<li><a href="https://twitter.com" target="_blank">||  Twitter</a></li>
				<li><a href="https://linkedin.com" target="_blank">||  Linkedin</a></li>
			</ul>
		</div>


		<div class="clearfix"> </div>
		<div class="copyright">
			<p>Copyrights © All rights reserved </p>
		</div>
	</div>

blogs/templates/blogs/index.html
{{% extends 'blogs/base.html' %}
{% load static %}

{% block content %}



<div class="container">
	<div class="col-md-9 bann-right">

		<!-- nam-matis -->
		<div class="nam-matis">
            {% for post in Blogs %}
			<div class="nam-matis-top">
                <div class="col-md-6 nam-matis-1">
                    <h3 class='font-weight-regular'><a href="{% url 'blogs:detail' post.id %}">{{ post.title }}</a></h3>
                    <h5 class="text-muted font-weight-light">
                        {{ post.author.first_name }}</a> | Published at: {{ post.created }} |

                      </h5>
                </div>
                <div class="description">
                    <p class="pl-0 pt-3 pr-3 pb-3 mt-3">
                        {{ post.body | truncatewords:"100" }}
                    </p>
                  </div>
                <div class="clearfix"> </div>
            </div>
            {% endfor %}

            <!-- {% for post in data %}
			<div class="nam-matis-top">
                <div class="col-md-6 nam-matis-1">
                    <a href="single.html"><img src="#" class="img-responsive" alt=""></a>
                    <h3><a href="#">{{ post.title }}</a></h3>
                    <p>{{post.content}}</p>
                </div>
                <div class="clearfix"> </div>
            </div>
            {% endfor %} -->
        </div>
    </div>
		<!-- nam-matis -->
	<div class="col-md-3 bann-left">
		<!-- <div class="b-search">
			<form>
				<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
				<input type="submit" value="">
			</form>
		</div> -->
        <h3>Recent Posts</h3>
        <!-- display latest blogs -->
		<div class="blo-top">
			<div class="blog-grids">
                {% for recent in featured %}
				<div class="blog-grid-left">
					<a href="single.html"><img src="{% static 'blogs/images/1.jpg' %} " class="img-responsive" alt=""></a>
				</div>
				<div class="blog-grid-right">
					<h4><a href="{% url 'blogs:detail' recent.id %}">{{ recent.title | truncatewords:"3" }} </a></h4>
					<p>{{ recent.body | truncatewords:"10" }} </p>
				</div>
                <div class="clearfix"> </div>
                {% endfor %}
			</div>

		</div>
        <h3>Authors</h3>
        <!-- display namelist of authors-->
		<div class="blo-top">
            {% for author in authors %}
			<li><a href="#">||   {{ author.first_name}}</a></li>
			<!-- <li><a href="#">||   Finibus Bonorum et</a></li>
			<li><a href="#">||   Treatise on the theory</a></li>
			<li><a href="#">||   Characteristic words</a></li>
			<li><a href="#">||   combined with a handful</a></li>
            <li><a href="#">||   which looks reasonable</a></li> -->
            {% endfor %}
		</div>


	</div>
	<div class="clearfix"> </div>

</div>
{% endblock content %}

blogs/templates/blogs/indexcopy.html
{{% extends 'blogs/base.html' %}

{% block content %}

<div class="container">
		<div class="col-md-9 bann-right">
		<!-- banner -->
		<div class="banner">
			<div class="header-slider">
				<div class="slider">
					<div class="callbacks_container">
					  	<ul class="rslides" id="slider">
							<li>
								<img src="../../static/Blogs/images/1.jpg" class="img-responsive" alt="">
								<div class="caption">
									<h3>Maecenas malesuada elit lectus felis</h3>
									<p>Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus.</p>
								</div>
							</li>
							<li>
								<img src="../../static/Blogs/images/4.jpg" class="img-responsive" alt="">
								<div class="caption">
									<h3>Curabitur et ligula. Ut molestie </h3>
									<p>Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulu. </p>
								</div>
							</li>
							<li>
								<img src="../../static/Blogs/images/5.jpg" class="img-responsive" alt="">
								<div class="caption">
									<h3>Etiam ullamcorper. Suspendisse</h3>
									<p>Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. </p>
								</div>
							</li>
							<li>
								<img src="../../static/Blogs/images/6.jpg" class="img-responsive" alt="">
								<div class="caption">
									<h3>Suspendisse a pellentesque dui</h3>
									<p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada .</p>
								</div>
							</li>
						</ul>
			  		</div>
				 </div>
			</div>
		</div>
		<!-- banner -->
		<!-- nam-matis -->
		<div class="nam-matis">
			<div class="nam-matis-top">
						<div class="col-md-6 nam-matis-1">
							<a href="single.html"><img src="../../static/Blogs/images/5.jpg" class="img-responsive" alt=""></a>
							<h3><a href="single.html">Suspendisse a pellentesque dui</a></h3>
							<p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula.</p>
						</div>
						<div class="col-md-6 nam-matis-1">
							<a href=""><img src="../../static/Blogs/images/6.jpg" class="img-responsive" alt=""></a>
							<h3><a href="">Suspendisse a pellentesque dui</a></h3>
							<p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula.</p>
						</div>
							<div class="clearfix"> </div>
				</div>
				<div class="nam-matis-top">
						<div class="col-md-6 nam-matis-1">
							<a href="single.html"><img src="../../static/Blogs/images/4.jpg" class="img-responsive" alt=""></a>
							<h3><a href="single.html">Suspendisse a pellentesque dui</a></h3>
							<p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula.</p>
						</div>
						<div class="col-md-6 nam-matis-1">
							<a href="single.html"><img src="../../static/Blogs/images/1.jpg" class="img-responsive" alt=""></a>
							<h3><a href="single.html">Suspendisse a pellentesque dui</a></h3>
							<p>Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula.</p>
						</div>
							<div class="clearfix"> </div>
					</div>
		</div>
		<!-- nam-matis -->
	</div>
	<div class="col-md-3 bann-left">
		<div class="b-search">
			<form>
				<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
				<input type="submit" value="">
			</form>
		</div>
		<h3>Recent Posts</h3>
		<div class="blo-top">
			<div class="blog-grids">
				<div class="blog-grid-left">
					<a href="single.html"><img src="../../static/Blogs/images/1b.jpg" class="img-responsive" alt=""></a>
				</div>
				<div class="blog-grid-right">
					<h4><a href="single.html">Little Invaders </a></h4>
					<p>pellentesque dui, non felis. Maecenas male </p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="blog-grids">
				<div class="blog-grid-left">
					<a href="single.html"><img src="../../static/Blogs/images/2b.jpg" class="img-responsive" alt=""></a>
				</div>
				<div class="blog-grid-right">
					<h4><a href="single.html">Little Invaders </a></h4>
					<p>pellentesque dui, non felis. Maecenas male </p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="blog-grids">
				<div class="blog-grid-left">
					<a href=""><img src="../../static/Blogs/images/3b.jpg" class="img-responsive" alt=""></a>
				</div>
				<div class="blog-grid-right">
					<h4><a href="single.html">Little Invaders </a></h4>
					<p>pellentesque dui, non felis. Maecenas male </p>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<h3>Authors</h3>
		<div class="blo-top">
<!--			{% for author in authors %}-->
<!--			<li><a href="#">||   {{ author.first_name|title}}</a></li>-->
<!--			{% endfor %}-->
		</div>



	</div>
	<div class="clearfix"> </div>
		<div class="fle-xsel">
			<ul id="flexiselDemo3">
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="../../static/Blogs/images/6.jpg" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="../../static/Blogs/images/5.jpg" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="../../static/Blogs/images/1.jpg" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="../../static/Blogs/images/4.jpg" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="../../static/Blogs/images/6.jpg" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="../../static/Blogs/images/1.jpg" class="img-responsive" alt="">
						</div>
					</a>
				</li>
			</ul>

							 <script type="text/javascript">
								$(window).load(function() {

									$("#flexiselDemo3").flexisel({
										visibleItems: 5,
										animationSpeed: 1000,
										autoPlay: true,
										autoPlaySpeed: 3000,
										pauseOnHover: true,
										enableResponsiveBreakpoints: true,
										responsiveBreakpoints: {
											portrait: {
												changePoint:480,
												visibleItems: 2
											},
											landscape: {
												changePoint:640,
												visibleItems: 3
											},
											tablet: {
												changePoint:768,
												visibleItems: 3
											}
										}
									});

								});
								</script>
								<script type="text/javascript" src="../../static/Blogs/js/jquery.flexisel.js"></script>
					<div class="clearfix"> </div>
		</div>

	</div>



{% endblock %}

blogs/templates/blogs/list_blog.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block content %}
<!-- header -->
	<!-- Blog -->
	<div class="container">
		<div class="blog">

		<div class="blog-content">
					<div class="blog-content-left">
						<div class="blog-articals">
						{% for blog in posts %}
						<div class="blog-artical">
							<div class="blog-artical-info">
								<div class="blog-artical-info-head">
									<h2><a href="#">{{ blog.title }}</a></h2>
									<h2>Posted on {{ blog.created }} by <a href="#">{{ blog.author_id }}</a></h2>
								</div>
								<div class="blog-artical-info-text">
									<p class="pl-0 pt-3 pr-3 pb-3 mt-3">{{ blog.body | truncatewords:"100" }}<a href="{% url 'blogs:detail' blog.id %}">[Read More]</a></p>
								</div>

							</div>
							<div class="clearfix"> </div>
						</div>
						{% endfor%}

					</div>
					<!--start-blog-pagenate-->
							<!-- <nav>
										  <ul class="pagination">
											<li>
											  <a href="#" aria-label="Previous">
												<span aria-hidden="true">«</span>
											  </a>
											</li>
											<li><a href="#">1</a></li>
											<li><a href="#">2</a></li>
											<li><a href="#">3</a></li>
											<li><a href="#">4</a></li>
											<li><a href="#">5</a></li>
											<li>
											  <a href="#" aria-label="Next">
												<span aria-hidden="true">»</span>
											  </a>
											</li>
										  </ul>
										</nav> -->
				<!--//End-blog-pagenate-->
					</div>

					</div>
					<div class="clearfix"> </div>

				</div>
		</div>
		<!-- /Blog -->


{% endblock content %}

blogs/templates/blogs/navbar.html
{% load static %}

<div class="header">
		<div class="container">
			<div class="blog-grid-left">
				<a href="#"><img src="#" class="img-responsive" alt=""></a>
			</div>

				<div class="head-nav">
					<span class="menu"> </span>
						<ul class="cl-effect-1">
							<li class="active"><a href="{% url 'blogs:display' %}">Home</a></li>

							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'useraccounts:blog_list' author=request.user.username author_id=request.user.id %}">
									Your Posts
								</a>
							</li>
							<li>
								<a href="{% url 'blogs:create' %}">
									Create Posts
								</a>
							</li>
							<li>
								<a class="navbar-link dropdown-toggle" href="{% url 'useraccounts:edit' author_id=request.user.id %}" role="button" data-toggle="dropdown">
									<img width="30px" height="30px" class="img-rounded"
										 src="{% static 'blogs/images/icon.svg' %} "
									alt="avatar" width="25" height="25" >
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown">
									<a class="dropdown-submenu" href="#">
										Edit Profile
									</a>

								<div class="dropdown-togglespan"></div>
								<a class="dropdown-submenu" href="{% url 'useraccounts:logout' %}">
									Logout
								</a>
								</div>
							</li>
<!--							<li class="nav-item avatar dropdown">-->
<!--        						<a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown"-->
<!--          								aria-haspopup="true" aria-expanded="false">-->
<!--          						<img src="" class="img-circle" width="25" height="25"-->
<!--            							alt="avatar image">-->
<!--        						</a>-->
<!--&lt;!&ndash;								rounded-circle z-depth-0&ndash;&gt;-->
<!--        						<div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary"-->
<!--          							aria-labelledby="navbarDropdownMenuLink-55">-->
<!--          						<a class="dropdown-item" href="#">Action</a>-->
<!--						        <a class="dropdown-item" href="#">Another action</a>-->
<!--          						<a class="dropdown-item" href="#">Something else here</a>-->
<!--        						</div>-->
<!--      						</li>-->

							<li><a href="{% url 'useraccounts:logout' %}">Logout</a></li>

							{% else %}

							<li><a href="{% url 'useraccounts:login' %}">Login</a></li>

							<li><a href="{% url 'useraccounts:signup' %}">Register</a></li>

										<div class="clearfix"></div>
							{% endif %}
						</ul>
				</div>
						<!-- script-for-nav -->
							<script>
								$( "span.menu" ).click(function() {
								  $( ".head-nav ul" ).slideToggle(300, function() {
									// Animation complete.
								  });
								});
							</script>
						<!-- script-for-nav -->



					<div class="clearfix"> </div>
		</div>
	</div>